version: '3'

services:
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: md-editor
    ports:
      - '3000:80'  # 映射到 nginx 的 80 端口
    restart: unless-stopped 